Repository mosn/proxy-wasm-go-host, pull requests merged in 2023-02, with the labels that each got.

#31 deps: updates wazero to 1.0.0-pre.8
  go.mod
  go.sum
  wazero/instance.go
  wazero/module.go
  wazero/vm.go
Labels: First-time contributor, cla:yes, size/M

#32 Ensures module lifecycle is tested prior to integration with mosn
  wasmer/instance_test.go
  wazero/instance.go
  wazero/instance_test.go
  wazero/module.go
  wazero/vm.go
Labels: cla:yes, size/L

#33 deps: updates wazero to 1.0.0-pre.9
  .github/workflows/workflow.yml
  go.mod
  go.sum
  wazero/instance.go
Labels: cla:yes, size/S
